// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzmbeiwsjkxxoaykaxzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bWJlaXdzamt4eG9heWtheHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyOTgyODksImV4cCI6MjA1Mzg3NDI4OX0.zHPdT25pVmN9CFeaBCjurRrzbbfcIIsBq51_OMmjrWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);